package paymentserver.HomePage;

import paymentserver.AccountManagement.*;
import paymentserver.AccountStatistic.*;

public class ServerHomePage extends javax.swing.JFrame {

    /**
     * Creates new form ServerHomePage
     */
    public ServerHomePage() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnStatistic = new javax.swing.JLabel();
        BtnAccount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnStatisticMouseClicked(evt);
            }
        });
        getContentPane().add(BtnStatistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 250, 80));

        BtnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAccountMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 250, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paymentserver/HomePage/PaymentAppServerHomeBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStatisticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnStatisticMouseClicked
        // TODO add your handling code here:
        AccountStatistic acs = new AccountStatistic();
        acs.show();
        dispose();
    }//GEN-LAST:event_BtnStatisticMouseClicked

    private void BtnAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAccountMouseClicked
        // TODO add your handling code here:
        AccountManagement acm = new AccountManagement();
        acm.show();
        dispose();
    }//GEN-LAST:event_BtnAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAccount;
    private javax.swing.JLabel BtnStatistic;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
