/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacovid19app.Admin.AdminHomePage;

import javacovid19app.Admin.AdminHomePage.ManagerAccountsManagement.ManagerAccountManagement;
import javacovid19app.Admin.AdminHomePage.TreatmentFacilitiesManagement.TreatmentFacilitiesManagement;
import javacovid19app.HomePage.HomePage;

/**
 *
 * @author tongt
 */
public class AdminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
        this.setResizable(false); // can not fix size of a Frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FacilitiesManagement = new javax.swing.JLabel();
        ManagerAccounts = new javax.swing.JLabel();
        BtnLogout = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FacilitiesManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacilitiesManagementMouseClicked(evt);
            }
        });
        getContentPane().add(FacilitiesManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 190, 300));

        ManagerAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManagerAccountsMouseClicked(evt);
            }
        });
        getContentPane().add(ManagerAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, 300));

        BtnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 60, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javacovid19app/Admin/AdminHomePage/AdminHomePageBackground(960x540).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManagerAccountsMouseClicked
        // TODO add your handling code here:
        ManagerAccountManagement mam = new ManagerAccountManagement();
        mam.show();
        dispose();
    }//GEN-LAST:event_ManagerAccountsMouseClicked

    private void FacilitiesManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacilitiesManagementMouseClicked
        // TODO add your handling code here:
        TreatmentFacilitiesManagement facilitiesManagerment = new TreatmentFacilitiesManagement();
        facilitiesManagerment.show();
        dispose();
    }//GEN-LAST:event_FacilitiesManagementMouseClicked

    private void BtnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogoutMouseClicked
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.show();
        dispose();
    }//GEN-LAST:event_BtnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnLogout;
    private javax.swing.JLabel FacilitiesManagement;
    private javax.swing.JLabel ManagerAccounts;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
