/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacovid19app.ManagedUser;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javacovid19app.HomePage.HomePage;
import javax.swing.JOptionPane;
import org.springframework.security.crypto.bcrypt.BCrypt;
import javacovid19app.ManagedUser.ManagedUserHomePage.*;

/**
 *
 * @author IVS-P0005
 */
public class ManagedUserSignIn extends javax.swing.JFrame {

    /**
     * Creates new form UserSignIn
     */
    public ManagedUserSignIn() {
        initComponents();
        this.setResizable(false); // can not fix size of a Frame;
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserID = new javax.swing.JTextField();
        UserPassword = new javax.swing.JPasswordField();
        BtnUserSignIn = new javax.swing.JLabel();
        BtnBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Sign In");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserID.setFont(new java.awt.Font("Fredoka One", 0, 18)); // NOI18N
        UserID.setForeground(new java.awt.Color(173, 0, 0));
        UserID.setBorder(null);
        UserID.setOpaque(false);
        getContentPane().add(UserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 350, 30));

        UserPassword.setFont(new java.awt.Font("Fredoka One", 0, 18)); // NOI18N
        UserPassword.setForeground(new java.awt.Color(173, 0, 0));
        UserPassword.setBorder(null);
        UserPassword.setOpaque(false);
        getContentPane().add(UserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 350, 30));

        BtnUserSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUserSignInMouseClicked(evt);
            }
        });
        getContentPane().add(BtnUserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 150, 50));

        BtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBackMouseClicked(evt);
            }
        });
        getContentPane().add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javacovid19app/ManagedUser/ManagedUserSignInBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUserSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUserSignInMouseClicked
        // TODO add your handling code here:
        // if User click Sign In
        // TODO add your handling code here:
        // check account for login admin services.

        String username = UserID.getText();
        String password = UserPassword.getText();

        if (username.isEmpty() && password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide username and password!");
        } else {
            try {
                //use SQL Query to update admin password.
                Class.forName("com.mysql.jdbc.Driver");
                Connection connect = DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6448649?useSSL = true", "sql6448649", "ygTCgTJZu6");
                Statement state = connect.createStatement();

                String sql = "Select Password from Account where UserID = '" + username + "' and Type = 3";
                ResultSet res = state.executeQuery(sql);

                if (res.next()) {
                    String real_pass = res.getString(1);
                    System.out.println(real_pass);
                    if (BCrypt.checkpw(password, real_pass) == true) {
                        JOptionPane.showMessageDialog(this, "Login successfully.");
                        ManagedUserHomePage homepage = new ManagedUserHomePage(username);
                        
                        homepage.show();
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Wrong username or password!");
                        UserID.setText("");
                        UserPassword.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong username or password!");
                    UserID.setText("");
                    UserPassword.setText("");
                }
                connect.close();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_BtnUserSignInMouseClicked

    private void BtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBackMouseClicked
        // TODO add your handling code here:
        dispose();
        HomePage home = new HomePage();
        home.show();
    }//GEN-LAST:event_BtnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagedUserSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagedUserSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagedUserSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagedUserSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagedUserSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnBack;
    private javax.swing.JLabel BtnUserSignIn;
    private javax.swing.JTextField UserID;
    private javax.swing.JPasswordField UserPassword;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
