/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacovid19app.Admin.AdminSignIn;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.springframework.security.crypto.bcrypt.BCrypt;

/**
 *
 * @author @khoung
 */
public class AdminSignInFirstTime extends javax.swing.JFrame {

    /**
     * Creates new form AdminSignInFirstTime
     */
    public AdminSignInFirstTime() {
        initComponents();
        this.setResizable(false); // can not fix size of a Frame;
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPassword = new javax.swing.JPasswordField();
        AdminConfirmPassword = new javax.swing.JPasswordField();
        BtnConfirmPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin First Time Sign In");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminPassword.setFont(new java.awt.Font("Fredoka One", 0, 18)); // NOI18N
        AdminPassword.setBorder(null);
        AdminPassword.setOpaque(false);
        getContentPane().add(AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 360, 30));

        AdminConfirmPassword.setFont(new java.awt.Font("Fredoka One", 0, 18)); // NOI18N
        AdminConfirmPassword.setBorder(null);
        AdminConfirmPassword.setOpaque(false);
        getContentPane().add(AdminConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 360, 30));

        BtnConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(BtnConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javacovid19app/Admin/AdminSignIn/AdmiSignInFirstTimeBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmPasswordMouseClicked
        // TODO add your handling code here:
        String newPass = AdminPassword.getText();
        String confirmPass = AdminConfirmPassword.getText();
        
        if (newPass.isEmpty() && confirmPass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your password!");
        }
        else{
            if (newPass.compareTo(confirmPass) == 0){
                try {
                    // hash Password usinng bcrypt.
                    String hashedPass =  BCrypt.hashpw(confirmPass, BCrypt.gensalt(8));
                    System.out.print("HashedPassword: " + hashedPass);

                    //use SQL Query to update admin password.
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection connect = DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6448649?useSSL = false", "sql6448649", "ygTCgTJZu6");
                    Statement state = connect.createStatement();

                    //update pass.
                    String sql_pass = "Update Account set Password = '"+hashedPass+"' where UserID = 'admin'";
                    state.executeUpdate(sql_pass);

                    //update activated.
                    String sql_activated = "Update Account set Status = 1 where UserID = 'admin'";
                    state.executeUpdate(sql_activated);

                    connect.close();
                    dispose();
                }catch(Exception e){
                System.out.println(e.getMessage());
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Confirm password is not the same!");
                AdminPassword.setText("");
                AdminConfirmPassword.setText("");

            }
        }
    }//GEN-LAST:event_BtnConfirmPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignInFirstTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignInFirstTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignInFirstTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignInFirstTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSignInFirstTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField AdminConfirmPassword;
    private javax.swing.JPasswordField AdminPassword;
    private javax.swing.JLabel BtnConfirmPassword;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
