/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacovid19app.HomePage;

import com.mysql.jdbc.PreparedStatement;
import javacovid19app.ManagedUser.ManagedUserSignIn;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javacovid19app.Manager.*;
import javacovid19app.Admin.AdminSignIn.*;


/**
 *
 * @author IVS-P0005
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.setResizable(false); // can not fix size of a Frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnManager = new javax.swing.JLabel();
        BtnAdmin = new javax.swing.JLabel();
        BtnUserActor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Covid-19 Information Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnManagerMouseClicked(evt);
            }
        });
        getContentPane().add(BtnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 150, 50));

        BtnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdminMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 150, 60));

        BtnUserActor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUserActorMouseClicked(evt);
            }
        });
        getContentPane().add(BtnUserActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javacovid19app/HomePage/HomePageBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnManagerMouseClicked
        // TODO add your handling code here:
        ManagerSignIn manager = new ManagerSignIn();
        manager.show();
        dispose();
        
        
    }//GEN-LAST:event_BtnManagerMouseClicked

   
    private void BtnAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdminMouseClicked
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection connect = DriverManager.getConnection("jdbc:mysql://sql6.freemysqlhosting.net:3306/sql6448649?useSSL = false", "sql6448649", "ygTCgTJZu6");
                Statement state = connect.createStatement();

                String sql = "Select * from Account where UserID = 'admin' and Status = 0";
                ResultSet res = state.executeQuery(sql);
                if (res.next()){
                    dispose();
                    AdminSignInFirstTime newAdmin = new AdminSignInFirstTime();
                    newAdmin.show();
                }
                else{
                    AdminSignInNTimes oldAdmin = new AdminSignInNTimes();
                    oldAdmin.show();
                }
                connect.close();
            }catch(Exception e){
            System.out.println(e.getMessage());
            }
        dispose();
    }//GEN-LAST:event_BtnAdminMouseClicked

    private void BtnUserActorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUserActorMouseClicked
        // TODO add your handling code here:
        // Choose USER ACTOR.
        
        ManagedUserSignIn managedUser = new ManagedUserSignIn();
        managedUser.show();
        dispose();
        
    }//GEN-LAST:event_BtnUserActorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAdmin;
    private javax.swing.JLabel BtnManager;
    private javax.swing.JLabel BtnUserActor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
